export interface Template {
  name: string;
  command: string;
  timeout: number;
  retries: number;
  schedule: string | null;
  desc: string;
  tags: string[];
}

export const TEMPLATES: Template[] = [
  // Observability — Disk
  {
    name: 'Disk Space Alert',
    command: 'df -h / | awk \'NR==2 {if ($5+0 > 90) {echo "ALERT: disk at $5"; exit 1} else {echo "OK: $5 used"}}\'',
    timeout: 15,
    retries: 0,
    schedule: '0 */6 * * *',
    desc: 'Alert if root disk exceeds 90%',
    tags: ['observability', 'disk'],
  },
  {
    name: 'Disk I/O Stats',
    command: 'iostat -d 1 3 2>/dev/null || echo "iostat not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Snapshot of disk I/O throughput and latency',
    tags: ['observability', 'disk'],
  },
  {
    name: 'Large Files Finder',
    command: 'find / -xdev -type f -size +500M -exec ls -lh {} \\; 2>/dev/null | sort -k5 -rh | head -20',
    timeout: 60,
    retries: 0,
    schedule: '0 4 * * 0',
    desc: 'Find files larger than 500MB',
    tags: ['observability', 'disk'],
  },
  {
    name: 'Inode Usage',
    command: 'df -i / | awk \'NR==2 {print "Inodes: " $5 " used (" $3 "/" $2 ")"}\'',
    timeout: 10,
    retries: 0,
    schedule: '0 */12 * * *',
    desc: 'Check inode usage — running out causes failures even with free space',
    tags: ['observability', 'disk'],
  },

  // Observability — Memory
  {
    name: 'Memory Check',
    command:
      'vm_stat | awk \'/Pages free/ {free=$3} /Pages active/ {active=$3} END {printf "Free: %.0f MB, Active: %.0f MB\\n", free*4096/1048576, active*4096/1048576}\'',
    timeout: 10,
    retries: 0,
    schedule: '*/30 * * * *',
    desc: 'Report free and active memory',
    tags: ['observability', 'memory'],
  },
  {
    name: 'Swap Usage',
    command: 'sysctl vm.swapusage 2>/dev/null || free -h 2>/dev/null | grep -i swap',
    timeout: 10,
    retries: 0,
    schedule: '0 */4 * * *',
    desc: 'Check swap memory usage — high swap indicates memory pressure',
    tags: ['observability', 'memory'],
  },
  {
    name: 'Top Memory Consumers',
    command: 'ps aux --sort=-%mem 2>/dev/null | head -11 || ps aux -m | head -11',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Top 10 processes by memory usage',
    tags: ['observability', 'memory', 'process'],
  },

  // Observability — CPU / Load
  {
    name: 'CPU Load Average',
    command: 'uptime',
    timeout: 5,
    retries: 0,
    schedule: '*/15 * * * *',
    desc: 'System load averages (1, 5, 15 min)',
    tags: ['observability', 'cpu'],
  },
  {
    name: 'Top CPU Consumers',
    command: 'ps aux --sort=-%cpu 2>/dev/null | head -11 || ps aux -r | head -11',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Top 10 processes by CPU usage',
    tags: ['observability', 'cpu', 'process'],
  },
  {
    name: 'CPU Temperature',
    command:
      'sudo powermetrics --samplers smc -i 1 -n 1 2>/dev/null | grep -i "CPU die" || sensors 2>/dev/null | grep -i temp || echo "Not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Read CPU temperature (macOS powermetrics or Linux sensors)',
    tags: ['observability', 'cpu'],
  },

  // Observability — Network
  {
    name: 'Open Ports',
    command: 'lsof -i -P -n | grep LISTEN | sort -k9',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'List all processes listening on network ports',
    tags: ['observability', 'network'],
  },
  {
    name: 'Network Connections',
    command: 'netstat -an 2>/dev/null | grep ESTABLISHED | wc -l | xargs -I{} echo "{} active connections"',
    timeout: 10,
    retries: 0,
    schedule: '*/30 * * * *',
    desc: 'Count active network connections',
    tags: ['observability', 'network'],
  },
  {
    name: 'DNS Resolution Test',
    command: 'time nslookup google.com 2>&1 | tail -4',
    timeout: 10,
    retries: 2,
    schedule: '*/10 * * * *',
    desc: 'Test DNS resolution speed',
    tags: ['observability', 'network'],
  },
  {
    name: 'Tailscale Status',
    command: '/Applications/Tailscale.app/Contents/MacOS/Tailscale status',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show all connected tailnet devices',
    tags: ['observability', 'network'],
  },
  {
    name: 'Bandwidth Test',
    command:
      'curl -s -o /dev/null -w "Speed: %{speed_download} bytes/sec\\nTime: %{time_total}s\\n" https://speed.cloudflare.com/__down?bytes=10000000',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Quick download speed test via Cloudflare',
    tags: ['observability', 'network'],
  },

  // Process Control
  {
    name: 'Zombie Processes',
    command:
      'ps aux | awk \'$8 ~ /Z/ {print $2, $11}\' | head -20; echo "---"; ps aux | awk \'$8 ~ /Z/\' | wc -l | xargs -I{} echo "{} zombie processes"',
    timeout: 15,
    retries: 0,
    schedule: '0 */2 * * *',
    desc: 'Find zombie processes that need cleanup',
    tags: ['process', 'recovery'],
  },
  {
    name: 'Runaway Process Killer',
    command: 'ps aux | awk \'$3 > 95 && $11 !~ /kernel/ {print "HIGH CPU:", $2, $11, $3"%"}\'',
    timeout: 15,
    retries: 0,
    schedule: '*/10 * * * *',
    desc: 'Detect processes using >95% CPU',
    tags: ['process', 'recovery'],
  },
  {
    name: 'Process Count by User',
    command: "ps aux | awk '{print $1}' | sort | uniq -c | sort -rn | head -10",
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Count processes grouped by user',
    tags: ['process', 'observability'],
  },
  {
    name: 'Long-Running Processes',
    command: "ps -eo pid,etime,comm | awk '$2 ~ /-/ {print}' | sort -k2 -r | head -15",
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Processes running for more than a day',
    tags: ['process', 'observability'],
  },

  // Recovery
  {
    name: 'Service Health Check',
    command: 'curl -sf http://localhost:5555/api/tailscale > /dev/null && echo "OK" || echo "FAILED"',
    timeout: 10,
    retries: 3,
    schedule: '*/5 * * * *',
    desc: 'Verify the Home Server API is responding',
    tags: ['recovery', 'network'],
  },
  {
    name: 'Restart Home Server',
    command: 'cd ~/Code/Personal/home-server && npm run dev &',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Restart the dev server if it crashed',
    tags: ['recovery'],
  },
  {
    name: 'Clear System Cache',
    command: 'sudo purge 2>/dev/null && echo "Memory cache purged" || echo "Requires sudo"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Free inactive memory (macOS purge)',
    tags: ['recovery', 'memory'],
  },
  {
    name: 'Kill Port 5555',
    command:
      'lsof -ti:5555 | xargs kill -9 2>/dev/null && echo "Killed processes on port 5555" || echo "No process on port 5555"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Force kill any process holding port 5555',
    tags: ['recovery', 'process'],
  },
  {
    name: 'Flush DNS Cache',
    command:
      'sudo dscacheutil -flushcache 2>/dev/null && sudo killall -HUP mDNSResponder 2>/dev/null && echo "DNS flushed" || systemd-resolve --flush-caches 2>/dev/null && echo "DNS flushed"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Flush DNS resolver cache',
    tags: ['recovery', 'network'],
  },

  // Maintenance
  {
    name: 'Log Rotation',
    command: 'find /tmp -name "*.log" -mtime +7 -delete && echo "Cleaned old logs"',
    timeout: 30,
    retries: 0,
    schedule: '0 3 * * 0',
    desc: 'Delete log files older than 7 days',
    tags: ['maintenance'],
  },
  {
    name: 'Temp File Cleanup',
    command: 'find /tmp -type f -atime +3 -delete 2>/dev/null; echo "Cleaned tmp files older than 3 days"',
    timeout: 30,
    retries: 0,
    schedule: '0 4 * * *',
    desc: 'Remove stale temp files',
    tags: ['maintenance', 'disk'],
  },
  {
    name: 'npm Cache Clean',
    command: 'npm cache clean --force 2>&1 && echo "npm cache cleared"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Free disk space from npm cache',
    tags: ['maintenance', 'disk'],
  },
  {
    name: 'Git Repo Status',
    command: 'cd ~/Code && for d in */; do echo "=== $d ===" && git -C "$d" status -s 2>/dev/null; done',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Check git status across all repos in ~/Code',
    tags: ['maintenance'],
  },
  {
    name: 'System Uptime Report',
    command:
      'echo "Uptime: $(uptime)"; echo "Boot: $(who -b 2>/dev/null || last reboot | head -1)"; echo "Users: $(who | wc -l | tr -d \" \") logged in"',
    timeout: 10,
    retries: 0,
    schedule: '0 8 * * *',
    desc: 'Daily system uptime and login summary',
    tags: ['observability'],
  },
  {
    name: 'Backup Disk Health',
    command:
      'diskutil info /Volumes/* 2>/dev/null | grep -E "Name|Total|Free|SMART" || lsblk -o NAME,SIZE,FSAVAIL,FSUSE% 2>/dev/null',
    timeout: 15,
    retries: 0,
    schedule: '0 6 * * *',
    desc: 'Check health of mounted volumes',
    tags: ['observability', 'disk', 'recovery'],
  },

  // Security / Audit
  {
    name: 'World-Writable Files',
    command: 'find / -type f -perm -002 2>/dev/null | head -20',
    timeout: 60,
    retries: 0,
    schedule: null,
    desc: 'Locate world-writable files in the system',
    tags: ['security', 'audit'],
  },
  {
    name: 'Login History',
    command: 'last -20 2>/dev/null || lastlog -t 20',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show recent login history',
    tags: ['security', 'audit'],
  },
  {
    name: 'Firewall Status',
    command: 'sudo pfctl -s all 2>/dev/null | head -20 || sudo ufw status 2>/dev/null || echo "No firewall found"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Check firewall rules and state',
    tags: ['security'],
  },
  {
    name: 'SSH Key Audit',
    command: 'find ~ -name "*.pub" -o -name "id_*" 2>/dev/null | grep -v ".git"',
    timeout: 20,
    retries: 0,
    schedule: null,
    desc: 'Locate SSH keys in home directory',
    tags: ['security', 'audit'],
  },
  {
    name: 'Failed Auth Attempts',
    command:
      'grep "Failed password" /var/log/auth.log 2>/dev/null | tail -10 || log show --predicate \'eventMessage contains "invalid"\' --last 1h 2>/dev/null | tail -10',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show recent failed authentication attempts',
    tags: ['security', 'log-analysis'],
  },
  {
    name: 'SUID Binaries Check',
    command: 'find /usr/bin /usr/local/bin -perm -u+s -type f 2>/dev/null',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Audit SUID binaries for security concerns',
    tags: ['security', 'audit'],
  },

  // Docker
  {
    name: 'Docker Containers',
    command:
      'docker ps -a --format "table {{.Names}}\\t{{.Status}}\\t{{.Image}}" 2>/dev/null || echo "Docker not available"',
    timeout: 15,
    retries: 1,
    schedule: null,
    desc: 'List all Docker containers with status',
    tags: ['docker'],
  },
  {
    name: 'Docker Images',
    command:
      'docker images --format "table {{.Repository}}:{{.Tag}}\\t{{.Size}}" 2>/dev/null || echo "Docker not available"',
    timeout: 15,
    retries: 1,
    schedule: null,
    desc: 'Show all Docker images and sizes',
    tags: ['docker'],
  },
  {
    name: 'Docker Disk Usage',
    command: 'docker system df 2>/dev/null || echo "Docker not available"',
    timeout: 20,
    retries: 1,
    schedule: null,
    desc: 'Display Docker system disk usage',
    tags: ['docker', 'disk'],
  },
  {
    name: 'Docker Prune',
    command: 'docker system prune -a --volumes -f 2>/dev/null && echo "Pruned" || echo "Docker not available"',
    timeout: 120,
    retries: 0,
    schedule: null,
    desc: 'Remove all unused Docker resources',
    tags: ['docker', 'maintenance'],
  },
  {
    name: 'Docker Latest Logs',
    command: 'docker logs --tail=50 $(docker ps -q | head -1) 2>/dev/null || echo "No running containers"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Fetch last 50 lines of latest container logs',
    tags: ['docker', 'log-analysis'],
  },

  // Git
  {
    name: 'Git Repo Sizes',
    command: 'du -sh .git 2>/dev/null && du -sh . 2>/dev/null || echo "Not a git repo"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show Git repo and working directory size',
    tags: ['git'],
  },
  {
    name: 'Stale Git Branches',
    command: 'git branch -vv 2>/dev/null | grep ": gone\\]" || echo "No stale branches"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Find branches with deleted upstream tracking',
    tags: ['git', 'maintenance'],
  },
  {
    name: 'Git Recent Activity',
    command: 'git log --oneline -10 2>/dev/null || echo "Not a git repo"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show last 10 commits',
    tags: ['git'],
  },
  {
    name: 'Git Uncommitted Changes',
    command: 'git status --short 2>/dev/null | wc -l | xargs -I{} echo "{} uncommitted changes"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Count uncommitted changes in working directory',
    tags: ['git'],
  },
  {
    name: 'Git GC',
    command: 'git gc --aggressive --prune=now 2>/dev/null && echo "GC completed" || echo "Not a git repo"',
    timeout: 120,
    retries: 0,
    schedule: null,
    desc: 'Run aggressive garbage collection on Git repo',
    tags: ['git', 'maintenance'],
  },

  // Database
  {
    name: 'SQLite Check',
    command: 'sqlite3 :memory: "SELECT sqlite_version();" && echo "SQLite OK" || echo "SQLite not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Verify SQLite installation and version',
    tags: ['database'],
  },
  {
    name: 'PostgreSQL Databases',
    command: 'psql -l -t 2>/dev/null || echo "PostgreSQL not accessible"',
    timeout: 15,
    retries: 1,
    schedule: null,
    desc: 'List PostgreSQL databases and sizes',
    tags: ['database'],
  },
  {
    name: 'Redis Info',
    command: 'redis-cli info server 2>/dev/null || echo "Redis not running"',
    timeout: 10,
    retries: 1,
    schedule: null,
    desc: 'Display Redis server information',
    tags: ['database'],
  },
  {
    name: 'MySQL Status',
    command: 'mysql -e "SELECT VERSION();" 2>/dev/null || echo "MySQL not running"',
    timeout: 15,
    retries: 1,
    schedule: null,
    desc: 'Check MySQL/MariaDB connection and version',
    tags: ['database'],
  },

  // macOS
  {
    name: 'Homebrew Update',
    command: 'brew update && brew outdated || echo "Homebrew not available"',
    timeout: 60,
    retries: 0,
    schedule: null,
    desc: 'Update Homebrew and list outdated packages',
    tags: ['macos', 'maintenance'],
  },
  {
    name: 'System Profiler',
    command: 'system_profiler SPHardwareDataType SPSoftwareDataType 2>/dev/null | head -30',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Display hardware and software system info',
    tags: ['macos'],
  },
  {
    name: 'Installed Apps',
    command: 'ls /Applications | wc -l | xargs -I{} echo "{} apps" && ls /Applications | head -20',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Count and list installed applications',
    tags: ['macos'],
  },
  {
    name: 'Spotlight Status',
    command: 'mdutil -s / 2>/dev/null || echo "Spotlight status unavailable"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Check macOS Spotlight indexing status',
    tags: ['macos'],
  },
  {
    name: 'Power Settings',
    command: 'pmset -g 2>/dev/null || echo "Power settings unavailable"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Display current power management settings',
    tags: ['macos'],
  },

  // SSL / Certs
  {
    name: 'SSL Cert Expiry',
    command:
      'echo | openssl s_client -servername example.com -connect example.com:443 2>/dev/null | openssl x509 -noout -dates',
    timeout: 20,
    retries: 0,
    schedule: null,
    desc: 'Check SSL certificate expiration date',
    tags: ['ssl', 'security'],
  },
  {
    name: 'Generate Self-Signed Cert',
    command:
      'openssl req -x509 -newkey rsa:4096 -keyout /tmp/key.pem -out /tmp/cert.pem -days 365 -nodes -subj "/CN=localhost" && echo "Generated in /tmp/"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Generate self-signed SSL certificate',
    tags: ['ssl', 'maintenance'],
  },
  {
    name: 'Localhost Cert Check',
    command:
      'echo | openssl s_client -connect localhost:443 2>/dev/null | openssl x509 -noout -text | head -20 || echo "No SSL on localhost:443"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Check SSL cert served by localhost',
    tags: ['ssl'],
  },

  // User Management
  {
    name: 'System Users',
    command: 'dscl . -list /Users | grep -v "^_" 2>/dev/null || awk -F: \'$3 >= 1000 {print $1}\' /etc/passwd',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'List non-system user accounts',
    tags: ['user-mgmt', 'audit'],
  },
  {
    name: 'Last Login Times',
    command: 'lastlog -t 30 2>/dev/null || last | head -20',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show user last login times',
    tags: ['user-mgmt', 'audit'],
  },
  {
    name: 'User Groups',
    command: 'id && groups',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show current user ID and group memberships',
    tags: ['user-mgmt'],
  },

  // Service Watchdog
  {
    name: 'Launchctl Services',
    command:
      'launchctl list 2>/dev/null | head -20 || systemctl list-units --type=service --state=running 2>/dev/null | head -20',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'List managed services (macOS/Linux)',
    tags: ['watchdog'],
  },
  {
    name: 'Port Connectivity Check',
    command:
      'for port in 80 443 3000 5555 8080; do (echo > /dev/tcp/localhost/$port) 2>/dev/null && echo "Port $port: OPEN" || echo "Port $port: CLOSED"; done',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Check if common ports are accessible',
    tags: ['watchdog', 'network'],
  },
  {
    name: 'Health Endpoint Ping',
    command:
      'curl -sf -o /dev/null -w "%{http_code}" http://localhost:5555/api/tailscale && echo " OK" || echo "FAILED"',
    timeout: 10,
    retries: 1,
    schedule: '*/5 * * * *',
    desc: 'Ping Home Server health endpoint',
    tags: ['watchdog'],
  },

  // Log Analysis
  {
    name: 'System Error Log',
    command:
      'log show --last 1h --predicate \'messageType == error\' 2>/dev/null | tail -20 || grep -i "error\\|fatal" /var/log/syslog 2>/dev/null | tail -20',
    timeout: 20,
    retries: 0,
    schedule: null,
    desc: 'Extract errors from recent system logs',
    tags: ['log-analysis'],
  },
  {
    name: 'Log File Sizes',
    command: 'du -sh /var/log/* 2>/dev/null | sort -h | tail -10',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show top 10 largest log files',
    tags: ['log-analysis', 'disk'],
  },
  {
    name: 'Auth Log Analysis',
    command:
      'grep -c "Failed password" /var/log/auth.log 2>/dev/null | xargs -I{} echo "{} failed attempts" || echo "Auth log not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Count failed logins from auth log',
    tags: ['log-analysis', 'security'],
  },
  {
    name: 'Recent Warnings',
    command:
      'log show --last 1h --predicate \'messageType == warning\' 2>/dev/null | tail -15 || grep -i "warning" /var/log/syslog 2>/dev/null | tail -15',
    timeout: 20,
    retries: 0,
    schedule: null,
    desc: 'Extract warnings from recent system logs',
    tags: ['log-analysis'],
  },

  // File Integrity
  {
    name: 'Recent File Changes',
    command: 'find /etc -type f -mtime -1 -ls 2>/dev/null | head -20 || echo "No recent changes in /etc"',
    timeout: 20,
    retries: 0,
    schedule: '0 6 * * *',
    desc: 'Find files in /etc modified in last 24 hours',
    tags: ['file-integrity', 'security'],
  },
  {
    name: 'Broken Symlinks',
    command:
      'find /usr/local -type l -exec test ! -e {} \\; -print 2>/dev/null | head -20 || echo "No broken symlinks"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Find broken symlinks in /usr/local',
    tags: ['file-integrity'],
  },
  {
    name: 'File Permission Audit',
    command: 'find /usr/local/bin -type f -perm -u+s 2>/dev/null | head -20 || echo "No SUID files found"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Find setuid files that could pose risks',
    tags: ['file-integrity', 'security'],
  },
  {
    name: 'Home Dir Size Breakdown',
    command: 'du -sh ~/* 2>/dev/null | sort -h | tail -15',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Show size of each directory in home',
    tags: ['file-integrity', 'disk'],
  },

  // ─── Redis ─────────────────────────────────────────────────────────────
  {
    name: 'Redis: Server Status',
    command: 'redis-cli info server 2>/dev/null | head -20 || echo "Redis not running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show Redis server version, uptime, and mode',
    tags: ['redis', 'database'],
  },
  {
    name: 'Redis: Memory Usage',
    command:
      'redis-cli info memory 2>/dev/null | grep -E "used_memory_human|maxmemory_human|mem_fragmentation" || echo "Redis not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Check Redis memory usage and fragmentation ratio',
    tags: ['redis', 'database'],
  },
  {
    name: 'Redis: Connected Clients',
    command: 'redis-cli info clients 2>/dev/null || echo "Redis not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show connected client count and blocked clients',
    tags: ['redis', 'database'],
  },
  {
    name: 'Redis: Key Count by DB',
    command: 'redis-cli info keyspace 2>/dev/null || echo "Redis not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show number of keys per Redis database',
    tags: ['redis', 'database'],
  },
  {
    name: 'Redis: Slow Log',
    command: 'redis-cli slowlog get 10 2>/dev/null || echo "Redis not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show 10 most recent slow queries',
    tags: ['redis', 'database'],
  },
  {
    name: 'Redis: Flush All (DANGER)',
    command: 'echo "Run: redis-cli FLUSHALL" && echo "⚠ This will delete ALL keys in ALL databases"',
    timeout: 5,
    retries: 0,
    schedule: null,
    desc: 'Print flush command — does not execute (safety)',
    tags: ['redis', 'database'],
  },
  {
    name: 'Redis: Ping Test',
    command: 'redis-cli ping 2>/dev/null && echo "Redis is responding" || echo "Redis not available"',
    timeout: 5,
    retries: 1,
    schedule: '*/5 * * * *',
    desc: 'Quick health check — PONG means alive',
    tags: ['redis', 'database', 'watchdog'],
  },
  {
    name: 'Redis: Save Snapshot',
    command: 'redis-cli bgsave 2>/dev/null && echo "Background save started" || echo "Redis not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Trigger background RDB snapshot save',
    tags: ['redis', 'database', 'maintenance'],
  },

  // ─── MongoDB ───────────────────────────────────────────────────────────
  {
    name: 'MongoDB: Server Status',
    command:
      'mongosh --eval "db.serverStatus().version" --quiet 2>/dev/null || mongod --version 2>/dev/null || echo "MongoDB not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show MongoDB version and status',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Database List',
    command:
      "mongosh --eval \"db.adminCommand('listDatabases').databases.forEach(d => print(d.name + ' — ' + (d.sizeOnDisk/1024/1024).toFixed(1) + ' MB'))\" --quiet 2>/dev/null || echo \"MongoDB not available\"",
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'List all databases with sizes',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Connection Count',
    command: 'mongosh --eval "db.serverStatus().connections" --quiet 2>/dev/null || echo "MongoDB not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show current and available connections',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Replica Set Status',
    command: 'mongosh --eval "rs.status()" --quiet 2>/dev/null || echo "Not a replica set or MongoDB not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Check replica set health and member states',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Current Operations',
    command:
      'mongosh --eval "db.currentOp().inprog.length + \' active operations\'" --quiet 2>/dev/null || echo "MongoDB not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Count currently running operations',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Storage Stats',
    command: 'mongosh --eval "JSON.stringify(db.stats(), null, 2)" --quiet 2>/dev/null || echo "MongoDB not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show storage statistics for current database',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Index Stats',
    command:
      "mongosh --eval \"db.getCollectionNames().forEach(c => { var s = db[c].stats(); print(c + ': ' + s.nindexes + ' indexes, ' + (s.totalIndexSize/1024/1024).toFixed(1) + ' MB') })\" --quiet 2>/dev/null || echo \"MongoDB not available\"",
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show index count and size per collection',
    tags: ['mongodb', 'database'],
  },
  {
    name: 'MongoDB: Compact Database',
    command:
      'echo "Run: mongosh --eval \\"db.runCommand({compact: \'collectionName\'})\\"" && echo "⚠ Compact requires collection name — edit before running"',
    timeout: 5,
    retries: 0,
    schedule: null,
    desc: 'Print compact command template (edit before use)',
    tags: ['mongodb', 'database', 'maintenance'],
  },

  // ─── PostgreSQL ────────────────────────────────────────────────────────
  {
    name: 'Postgres: Database Sizes',
    command:
      'psql -c "SELECT datname, pg_size_pretty(pg_database_size(datname)) as size FROM pg_database ORDER BY pg_database_size(datname) DESC;" 2>/dev/null || echo "PostgreSQL not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'List all databases with human-readable sizes',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Active Connections',
    command:
      'psql -c "SELECT count(*) as total, state FROM pg_stat_activity GROUP BY state;" 2>/dev/null || echo "PostgreSQL not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show connection count grouped by state',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Long-Running Queries',
    command:
      'psql -c "SELECT pid, now() - pg_stat_activity.query_start AS duration, query FROM pg_stat_activity WHERE state = \'active\' AND now() - pg_stat_activity.query_start > interval \'5 seconds\' ORDER BY duration DESC LIMIT 5;" 2>/dev/null || echo "PostgreSQL not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Find queries running longer than 5 seconds',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Table Sizes',
    command:
      "psql -c \"SELECT schemaname, tablename, pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) as size FROM pg_tables WHERE schemaname = 'public' ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC LIMIT 15;\" 2>/dev/null || echo \"PostgreSQL not available\"",
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Top 15 largest tables by total size',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Cache Hit Ratio',
    command:
      'psql -c "SELECT sum(heap_blks_read) as disk_reads, sum(heap_blks_hit) as cache_hits, round(sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read))::numeric * 100, 2) as ratio FROM pg_statio_user_tables;" 2>/dev/null || echo "PostgreSQL not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Check buffer cache hit ratio (should be >99%)',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Vacuum Status',
    command:
      'psql -c "SELECT schemaname, relname, last_vacuum, last_autovacuum, n_dead_tup FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 10;" 2>/dev/null || echo "PostgreSQL not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Tables with most dead tuples needing vacuum',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Replication Status',
    command:
      'psql -c "SELECT * FROM pg_stat_replication;" 2>/dev/null || echo "No replication configured or PostgreSQL not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Check streaming replication lag and status',
    tags: ['postgres', 'database'],
  },
  {
    name: 'Postgres: Version & Uptime',
    command:
      'psql -c "SELECT version();" 2>/dev/null && psql -c "SELECT pg_postmaster_start_time(), now() - pg_postmaster_start_time() as uptime;" 2>/dev/null || echo "PostgreSQL not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show PostgreSQL version and server uptime',
    tags: ['postgres', 'database'],
  },

  // ─── Homebrew ──────────────────────────────────────────────────────────
  {
    name: 'Brew: Outdated Packages',
    command: 'brew outdated 2>/dev/null || echo "Homebrew not installed"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'List packages with available updates',
    tags: ['homebrew', 'macos', 'maintenance'],
  },
  {
    name: 'Brew: Doctor',
    command: 'brew doctor 2>&1 | head -30 || echo "Homebrew not installed"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Run diagnostics on Homebrew installation',
    tags: ['homebrew', 'macos'],
  },
  {
    name: 'Brew: Installed Packages',
    command:
      'brew list --formula 2>/dev/null | wc -l | xargs -I{} echo "{} formula installed" && brew list --cask 2>/dev/null | wc -l | xargs -I{} echo "{} casks installed" || echo "Homebrew not installed"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Count installed formulae and casks',
    tags: ['homebrew', 'macos'],
  },
  {
    name: 'Brew: Cleanup',
    command:
      'brew cleanup -n 2>/dev/null | tail -5 && echo "---" && brew cleanup --prune=7 -n 2>/dev/null | tail -3 || echo "Homebrew not installed"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Preview what cleanup would remove (dry run)',
    tags: ['homebrew', 'macos', 'maintenance'],
  },
  {
    name: 'Brew: Services List',
    command: 'brew services list 2>/dev/null || echo "Homebrew not installed"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show all Homebrew-managed services and their status',
    tags: ['homebrew', 'macos', 'watchdog'],
  },
  {
    name: 'Brew: Disk Usage',
    command: 'du -sh $(brew --cellar) $(brew --caskroom) 2>/dev/null || echo "Homebrew not installed"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Show disk space used by Homebrew cellar and caskroom',
    tags: ['homebrew', 'macos', 'disk'],
  },
  {
    name: 'Brew: Dependency Tree',
    command: 'brew deps --tree --installed 2>/dev/null | head -40 || echo "Homebrew not installed"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Show dependency tree of installed packages',
    tags: ['homebrew', 'macos'],
  },
  {
    name: 'Brew: Update All',
    command: 'brew update && brew upgrade 2>&1 | tail -20 || echo "Homebrew not installed"',
    timeout: 120,
    retries: 0,
    schedule: null,
    desc: 'Update Homebrew and upgrade all packages',
    tags: ['homebrew', 'macos', 'maintenance'],
  },

  // ─── Node.js / npm ─────────────────────────────────────────────────────
  {
    name: 'Node: Version Info',
    command: 'echo "Node: $(node -v)" && echo "npm: $(npm -v)" && echo "npx: $(npx -v 2>/dev/null || echo N/A)"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show Node.js, npm, and npx versions',
    tags: ['node', 'dev'],
  },
  {
    name: 'Node: Global Packages',
    command: 'npm list -g --depth=0 2>/dev/null',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'List globally installed npm packages',
    tags: ['node', 'dev'],
  },
  {
    name: 'Node: Cache Size',
    command: 'du -sh $(npm config get cache) 2>/dev/null || echo "Cannot determine npm cache"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show npm cache disk usage',
    tags: ['node', 'dev', 'disk'],
  },
  {
    name: 'Node: Audit Project',
    command: 'npm audit --omit=dev 2>/dev/null | tail -20 || echo "Not in a Node project"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Run security audit on current project dependencies',
    tags: ['node', 'dev', 'security'],
  },
  {
    name: 'Node: Running Processes',
    command: 'pgrep -fl "node " | head -15 || echo "No Node processes running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'List all running Node.js processes',
    tags: ['node', 'dev', 'process'],
  },
  {
    name: 'Node: Port Usage',
    command: 'lsof -iTCP -sTCP:LISTEN -n -P 2>/dev/null | grep node | head -10 || echo "No Node processes listening"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show ports used by Node.js processes',
    tags: ['node', 'dev', 'network'],
  },
  {
    name: 'Node: nvm List',
    command: 'source ~/.nvm/nvm.sh 2>/dev/null && nvm list 2>/dev/null || echo "nvm not installed"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'List installed Node versions via nvm',
    tags: ['node', 'dev'],
  },
  {
    name: 'Node: Kill All',
    command: 'pkill -f "node " && echo "All Node processes killed" || echo "No Node processes to kill"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Kill all running Node.js processes',
    tags: ['node', 'dev', 'process'],
  },

  // ─── Python ────────────────────────────────────────────────────────────
  {
    name: 'Python: Version Info',
    command: 'python3 --version && pip3 --version 2>/dev/null || echo "Python3 not available"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show Python and pip versions',
    tags: ['python', 'dev'],
  },
  {
    name: 'Python: Installed Packages',
    command: 'pip3 list 2>/dev/null | head -30 || echo "pip3 not available"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'List installed Python packages',
    tags: ['python', 'dev'],
  },
  {
    name: 'Python: Outdated Packages',
    command: 'pip3 list --outdated 2>/dev/null | head -20 || echo "pip3 not available"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Show packages with available updates',
    tags: ['python', 'dev'],
  },
  {
    name: 'Python: Virtual Envs',
    command: 'find ~/Code -name "pyvenv.cfg" -maxdepth 3 2>/dev/null | head -10 || echo "No venvs found"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Find Python virtual environments in ~/Code',
    tags: ['python', 'dev'],
  },
  {
    name: 'Python: Running Processes',
    command: 'pgrep -fl "python" | head -10 || echo "No Python processes running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'List all running Python processes',
    tags: ['python', 'dev', 'process'],
  },
  {
    name: 'Python: Cache Cleanup',
    command:
      'find ~/Code -type d -name "__pycache__" 2>/dev/null | wc -l | xargs -I{} echo "{} __pycache__ directories found"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Count __pycache__ directories (run with -delete to clean)',
    tags: ['python', 'dev', 'maintenance'],
  },
  {
    name: 'Python: Pip Cache Size',
    command:
      'pip3 cache info 2>/dev/null || du -sh ~/Library/Caches/pip 2>/dev/null || echo "Cannot determine pip cache"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show pip download cache size',
    tags: ['python', 'dev', 'disk'],
  },
  {
    name: 'Python: Security Check',
    command:
      'pip3 audit 2>/dev/null || pip-audit 2>/dev/null || echo "pip-audit not installed (pip install pip-audit)"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Audit installed packages for known vulnerabilities',
    tags: ['python', 'dev', 'security'],
  },

  // ─── Docker ────────────────────────────────────────────────────────────
  {
    name: 'Docker: Resource Usage',
    command:
      'docker stats --no-stream --format "table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}\\t{{.NetIO}}" 2>/dev/null || echo "Docker not running"',
    timeout: 15,
    retries: 0,
    schedule: null,
    desc: 'Snapshot of container CPU, memory, and network',
    tags: ['docker', 'dev'],
  },
  {
    name: 'Docker: Volume List',
    command: 'docker volume ls --format "table {{.Name}}\\t{{.Driver}}" 2>/dev/null || echo "Docker not running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'List all Docker volumes',
    tags: ['docker', 'dev'],
  },
  {
    name: 'Docker: Network List',
    command:
      'docker network ls --format "table {{.Name}}\\t{{.Driver}}\\t{{.Scope}}" 2>/dev/null || echo "Docker not running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'List Docker networks with driver info',
    tags: ['docker', 'dev'],
  },
  {
    name: 'Docker: Compose Status',
    command: 'docker compose ps 2>/dev/null || docker-compose ps 2>/dev/null || echo "No compose project running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show status of docker-compose services',
    tags: ['docker', 'dev'],
  },
  {
    name: 'Docker: Build Cache',
    command: 'docker builder prune --all -f 2>/dev/null && echo "Build cache cleared" || echo "Docker not running"',
    timeout: 30,
    retries: 0,
    schedule: null,
    desc: 'Clear Docker build cache to free disk',
    tags: ['docker', 'dev', 'maintenance'],
  },
  {
    name: 'Docker: Dangling Images',
    command:
      'docker images -f "dangling=true" -q 2>/dev/null | wc -l | xargs -I{} echo "{} dangling images" || echo "Docker not running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Count untagged/dangling images',
    tags: ['docker', 'dev'],
  },
  {
    name: 'Docker: Container Logs (Last)',
    command: 'LAST=$(docker ps -lq 2>/dev/null) && docker logs --tail=30 $LAST 2>/dev/null || echo "No containers"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Last 30 lines of most recently started container',
    tags: ['docker', 'dev', 'log-analysis'],
  },
  {
    name: 'Docker: System Events',
    command:
      'timeout 5 docker events --since 1h --format "{{.Time}} {{.Action}} {{.Type}}/{{.Actor.Attributes.name}}" 2>/dev/null | tail -20 || echo "Docker not running"',
    timeout: 10,
    retries: 0,
    schedule: null,
    desc: 'Show Docker events from the last hour',
    tags: ['docker', 'dev'],
  },
];
