<script lang="ts">
  import {
    Save,
    Plus,
    Trash2,
    Pencil,
    RefreshCw,
    Search,
    X,
    ChevronDown,
    ChevronRight,
    Star,
    Play,
    Pause,
    Square,
    Copy,
    Download,
    Upload,
    Settings,
    HelpCircle,
    Terminal,
    File,
    Folder,
    Check,
    AlertTriangle,
    AlertCircle,
    Info,
    Link,
    ExternalLink,
    Menu,
    Filter,
    ArrowUpDown,
    ArrowUp,
    ArrowDown,
    Home,
    LayoutGrid,
    List,
    Send,
    Maximize2,
    Minimize2,
    Wifi,
    Bluetooth,
    Network,
    Cpu,
    MemoryStick,
    HardDrive,
    Clock,
    Calendar,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Share2,
    QrCode,
    Bookmark,
    Columns3,
    Power,
    Globe,
    ArrowLeft,
    ArrowRight,
    SkipBack,
    SkipForward,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    GripVertical,
    PictureInPicture2,
    Zap,
    Monitor,
    Printer,
    Camera,
    Battery,
    Usb,
    Headphones,
    Signal,
    Shield,
    Loader2,
    MoreHorizontal,
    ChevronUp,
    Hash,
    FolderOpen,
    FileText,
    Image,
    Film,
    Music,
    Archive,
    Code2,
    Type,
    Sun,
    Moon,
    Palette,
    SlidersHorizontal,
    RotateCw,
    Plug,
    Radio,
  } from 'lucide-svelte';

  let {
    name,
    size = 16,
    class: className = '',
  } = $props<{
    name: string;
    size?: number;
    class?: string;
  }>();

  const ICON_MAP: Record<string, any> = {
    save: Save,
    add: Plus,
    delete: Trash2,
    edit: Pencil,
    refresh: RefreshCw,
    search: Search,
    close: X,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    star: Star,
    'star-filled': Star,
    play: Play,
    pause: Pause,
    stop: Square,
    copy: Copy,
    download: Download,
    upload: Upload,
    settings: Settings,
    help: HelpCircle,
    terminal: Terminal,
    file: File,
    folder: Folder,
    'folder-open': FolderOpen,
    check: Check,
    warning: AlertTriangle,
    error: AlertCircle,
    info: Info,
    link: Link,
    'external-link': ExternalLink,
    menu: Menu,
    filter: Filter,
    'sort-asc': ArrowUp,
    'sort-desc': ArrowDown,
    sort: ArrowUpDown,
    home: Home,
    grid: LayoutGrid,
    list: List,
    send: Send,
    maximize: Maximize2,
    minimize: Minimize2,
    wifi: Wifi,
    bluetooth: Bluetooth,
    network: Network,
    cpu: Cpu,
    memory: MemoryStick,
    disk: HardDrive,
    clock: Clock,
    calendar: Calendar,
    eye: Eye,
    'eye-off': EyeOff,
    lock: Lock,
    unlock: Unlock,
    share: Share2,
    qr: QrCode,
    bookmark: Bookmark,
    kanban: Columns3,
    wol: Power,
    power: Power,
    dns: Globe,
    globe: Globe,
    port: Shield,
    speed: Zap,
    clipboard: Copy,
    screenshot: Camera,
    benchmark: Cpu,
    packet: Radio,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'skip-back': SkipBack,
    'skip-forward': SkipForward,
    volume: Volume,
    'volume-low': Volume1,
    'volume-high': Volume2,
    'volume-off': VolumeX,
    grip: GripVertical,
    pip: PictureInPicture2,
    monitor: Monitor,
    printer: Printer,
    camera: Camera,
    battery: Battery,
    usb: Usb,
    headphones: Headphones,
    signal: Signal,
    loader: Loader2,
    more: MoreHorizontal,
    hash: Hash,
    'file-text': FileText,
    image: Image,
    film: Film,
    music: Music,
    archive: Archive,
    code: Code2,
    type: Type,
    sun: Sun,
    moon: Moon,
    palette: Palette,
    sliders: SlidersHorizontal,
    rotate: RotateCw,
    plug: Plug,
  };

  const component = $derived(ICON_MAP[name] || HelpCircle);
</script>

<span class="icon {className}" style="display: inline-flex; align-items: center; justify-content: center;">
  <svelte:component this={component} {size} strokeWidth={1.75} />
</span>

<style>
  .icon {
    line-height: 0;
  }

  .icon :global(svg) {
    vertical-align: middle;
  }
</style>
